### ISSUE TITLE
wpparser-1.1.1 on pypi is missing pip.req

### ISSUE THREAD

**Issue by swharden** [marteinn/wpparser#2]
This script is great! I wish the version on pypi worked.

The latest version is wpparser-1.1.1 https://pypi.org/project/wpparser/#files

This has an error in its setup.py where it seeks pip.req (not in manifest):
```python
from pip.req import parse_requirements
```

The setup.py in the current repository looks much improved! Please upload a working package to pypi (or delete the ones that are there?) Thanks!

**Comment by marteinn** [comment]
Hi @swharden! Thanks for letting me know, I just pushed out a new release (1.1.2) that should resolve this issue. Cheers!

**Comment by swharden** [comment]
Fantastic, I tested it and it installs as expected from pip - thanks @marteinn!
